workflows:
  quotekit-workflow:
    name: QuoteKit Building and Testing Workflow
    environment:
      xcode: latest
      vars:
        SCHEME: QuoteKit
        DESTINATION: "platform=iOS Simulator,OS=16.2,name=iPhone 14"
    triggering:
      events:
        - push
    scripts:
      - name: Build Framework
        script: |
          xcodebuild \
            -scheme $XCODE_SCHEME \
            -destination "$DESTINATION" \
            -skipPackagePluginValidation \
            clean build
      - name: Test Framework
        script: |
          set -o pipefail
          xcodebuild \
            -scheme $XCODE_SCHEME \
            -destination "$DESTINATION" \
            -skipPackagePluginValidation \
            test | xcpretty --report junit
