workflows:
  quotekit-test-workflow:
    environment:
      xcode: latest
      vars:
        SCHEME: "QuoteKit"
        DESTINATION: "platform=iOS Simulator,OS=15.0,name=iPhone 12"
    triggering:
      events:
        - push
    scripts:
      - name: Test QuoteKit
        script: |
          xcodebuild -scheme $SCHEME -destination $DESTINATION test | xcpretty
