workflows:
  quotekit-workflow:
    name: QuoteKit Building and Testing Workflow
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      vars:
        XCODE_SCHEME: QuoteKit
    triggering:
      events:
        - push
    scripts:
      - name: Build Framework
        script: |
          #!/bin/zsh

          declare -a DESTINATIONS=("platform=iOS Simulator,name=iPhone 16" "platform=watchOS Simulator,name=Apple Watch Series 10 (46mm)" "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" "platform=macOS")
          for DESTINATION in "${DESTINATIONS[@]}"
            do
              xcodebuild clean build \
                -scheme "$XCODE_SCHEME" \
                -destination "$DESTINATION" \
                -skipPackagePluginValidation
          done
      - name: Test Framework
        script: |
          #!/bin/zsh
          
          declare -a DESTINATIONS=("platform=iOS Simulator,name=iPhone 16" "platform=watchOS Simulator,name=Apple Watch Series 10 (46mm)" "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" "platform=macOS")
          for DESTINATION in "${DESTINATIONS[@]}"
            do
              set -o pipefail
              xcodebuild clean test \
                -scheme "$XCODE_SCHEME" \
                -destination "$DESTINATION" \
                -skipPackagePluginValidation | xcpretty --report junit
          done
        test_report: build/reports/junit.xml
