name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2
    - name: Use latest Xcode
      run: sudo xcode-select -s '/Applications/Xcode_13.0.app/Contents/Developer'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: xcodebuild -scheme RRQuotableKit -destination 'platform:iOS Simulator, OS:15.0, name:iPhone 12' test | xcpretty
